version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - selenium
      
    ports:
    - 8000:8000

  selenium:
    image: selenium/standalone-chrome-debug:3.7.1
    ports:
      - 4444:4444
      - 5900:5900

