# Generated by Django 3.2.11 on 2022-01-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_locationmodel_json_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='address',
            field=models.CharField(help_text='"address":"8236 SW 1st St, Blue Springs, MO 64014"', max_length=300),
        ),
    ]
