# Generated by Django 3.2.11 on 2022-01-11 19:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_locationmodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationmodel',
            name='json_file',
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='json_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
